### ISSUE TITLE
An example issue

### ISSUE THREAD

**Issue by LynneKirsch** [DarkRisings/src#1]
This is an example issue submitted by a person that does not have permissions to the DarkRisings repository.

**Comment by DarkRisings** [comment]
Once an issue has been created, an admin on the repo can assign it to a project or close the issue entirely.

**Comment by LynneKirsch** [comment]
People can vote for issues using reactions and of course comments.
Admins on the repo can sort issues by reactions/comments to get a sense of what people want most.
