### ISSUE TITLE
Decide on a New Name

### ISSUE THREAD

**Issue by DarkRisings** [DarkRisings/src#5]
We need a new name for this game, since it is a branch of Dark Risings and we plan to evolve it in our own direction existing alongside the "Real" Dark Risings.

You can put reactions on comments. So, each of you can submit your idea for the game name and add your reactions to ones you like. We'll just use the one with the highest updoots.

I'll comment the suggestions already put forth.

**Comment by DarkRisings** [comment]
A Splice in Time

**Comment by DarkRisings** [comment]
Exiled

**Comment by Draban** [comment]
A Path to Exile

**Comment by trseagro** [comment]
Cataclysm

**Comment by figgers3036** [comment]
Rhia's Hope

**Comment by LynneKirsch** [comment]
Rhia's Exodus

**Comment by trseagro** [comment]
Vale of the Lost
