### ISSUE TITLE
Make it Public - Annoucnement

### ISSUE THREAD

**Issue by DarkRisings** [DarkRisings/src#6]
We have a solid annoucnement started that needs to be weighed in on and approved by everyone. Once it is, we will post it to the Alum page. We need to decide when we want to do that, as well. Also feel free to discuss other options. Below is the current annoucnement, but first here are the people who've already Green lit it:

- [x] Lynne
- [x] Valerie
- [x] Justin
- [x] John
- [ ] Dominic
- [ ] Sam

**To All it May Concern**
There is an alternative to Dark Risings now in production at 174.138.76.27 | 1313. It is complete with all areas, code, player files, and histories you remember, as well as a full staff including Admin/Imp/Coder/RP. There are about 9 of us. 9 players on an already thinning player base that were driven away. The new game is called a Splice in Time, and is a branch of Dark Risings existing in historical lore from a point before the new regime.

**OUR OPENING STATEMENT**
The existing staff of DR does, we are sure, mean well. However, we find ourselves at a place where many of us are banned from the game, due to transgressions as old as 3 years. Others of us have had the stories we worked so hard to build, in some cases for over a decade, torn away from us. Still others have had our characters stripped of dignity and thrown out of guilds we patroned for literal decades. The rest were repulsed by downright puerile acts of power grabbing.  Our opinions and contributions didn’t matter, our characters didn’t fit someone else’s vision, and it was made clear to us that we had no home at DR anymore.

And we're told we can't ever have it back. We're either told we're not welcome to play their game anymore, or we feel that it isn't the same, and doesn't satisfy the nostalgia that kept us coming back for so many years. And they are unwilling to work with us or negotiate at all in any way that’s significant.

But this game belongs to ALL OF US, not 2 people. So together we have come up with a vision statement and mission statement for where we want to take the game ourselves. It all boils down to the same thing: What's good for the players. 

So going into this, we promise a few things:
No more arbitrary bans or rule enforcement.  We will be transparent.
Old bans are rescinded.  We are looking for a fresh start.
We will be transparent about the codebase and coming changes.  It’s important to us that you understand how the game you play works.
Guilds will be run by mortal leadership.  You ultimately make this game fun, and should be running the guilds you choose to join to make that happen.
Staff will consist of an IMP, an Admin, a Coder, and a couple of imms for roleplay and general purposes that make your experience more interactive and fun. We want to strip away the old corruption that plagued DR’s staff from time to time, and create an environment where it cannot reappear.

To see our full action plan, policies mission/vision statement and ideas in the pipelines, go here: <link tbd>

All are welcome to login with your main characters, they still exist and are not banned. See you soon.

Viva la Resistance

**Comment by Draban** [comment]
I like it.
